// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7m8KO9gQkINm_qk_KSKUN9csVL_ofe4k',
    appId: '1:1069877584891:web:d2c7cb332ebf3574bea15e',
    messagingSenderId: '1069877584891',
    projectId: 'chat-app-c9b98',
    authDomain: 'chat-app-c9b98.firebaseapp.com',
    storageBucket: 'chat-app-c9b98.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTDQ4-tNlgc8tWl7gknG1dsBbQN_mBRqI',
    appId: '1:1069877584891:android:4b9d8e0be9fcc5dfbea15e',
    messagingSenderId: '1069877584891',
    projectId: 'chat-app-c9b98',
    storageBucket: 'chat-app-c9b98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxSrkmJzApTOzBWTIRjRBSBamNTxKTVXQ',
    appId: '1:1069877584891:ios:6fbf28ccec383b5bbea15e',
    messagingSenderId: '1069877584891',
    projectId: 'chat-app-c9b98',
    storageBucket: 'chat-app-c9b98.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxSrkmJzApTOzBWTIRjRBSBamNTxKTVXQ',
    appId: '1:1069877584891:ios:6fbf28ccec383b5bbea15e',
    messagingSenderId: '1069877584891',
    projectId: 'chat-app-c9b98',
    storageBucket: 'chat-app-c9b98.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7m8KO9gQkINm_qk_KSKUN9csVL_ofe4k',
    appId: '1:1069877584891:web:bd88495ae18b6f46bea15e',
    messagingSenderId: '1069877584891',
    projectId: 'chat-app-c9b98',
    authDomain: 'chat-app-c9b98.firebaseapp.com',
    storageBucket: 'chat-app-c9b98.firebasestorage.app',
  );
}
